name: Feature Request / Enhancement
description: Suggest an idea or enhancement for this addon.
body:
  - type: dropdown
    id: wow-version
    attributes:
      label: Game Version
      options:
        - All Versions
        - Retail
        - Mist of Pandaria - Classic
        - Burning Crusade - Classic Anniversary Edition
        - Classic
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Explain your idea. You can drag and drop mockup screenshots here.
    validations:
      required: true
